setTimeout(()=>{
    console.log("one");
},1000);setTimeout(()=>{
    console.log("two");
},2000);
setTimeout(()=>{
    console.log("three");
},3000);
setTimeout(()=>{
    console.log("Go!!");
},4000);